<?php
require_once ZOLO_DIR_PATH . 'includes/Blocks/PostGrid.php';
require_once ZOLO_DIR_PATH . 'includes/Blocks/PostList.php';

return apply_filters('zolo_blocks_list_data', [
    'container'          => ['name' => 'container'],
    'accordion'          => ['name' => 'accordion'],
    'accordion-child'    => ['name' => 'accordion-child'],
    'advanced-button'    => ['name' => 'advanced-button'],
    'advanced-heading'   => ['name' => 'advanced-heading'],
    'advanced-icon-box'  => ['name' => 'advanced-icon-box'],
    'advanced-image'     => ['name' => 'advanced-image'],
    'advanced-search'    => ['name' => 'advanced-search'],
    'brand-child'        => ['name' => 'brand-child'],
    'brand-grid'         => ['name' => 'brand-grid'],
    'business-hour'      => ['name' => 'business-hour'],
    'charts'             => ['name' => 'charts'],
    'countdown'          => ['name' => 'countdown'],
    'counter'            => ['name' => 'counter'],
    'cta'                => ['name' => 'cta'],
    'email'              => ['name' => 'email'],
    'fancy-list'         => ['name' => 'fancy-list'],
    'fancy-list-child'   => ['name' => 'fancy-list-child'],
    'flipbox'            => ['name' => 'flipbox'],
    'form'               => ['name' => 'form'],
    'google-map'         => ['name' => 'google-map'],
    'icon'               => ['name' => 'icon'],
    'image-compare'      => ['name' => 'image-compare'],
    'image-gallery'      => ['name' => 'image-gallery'],
    'list'               => ['name' => 'list'],
    'newsletter'         => ['name' => 'newsletter'],
    'notice'             => ['name' => 'notice'],
    'popup-builder'      => ['name' => 'popup-builder'],
    'post-carousel'      => ['name' => 'post-carousel', 'class' => '\Zolo\Blocks\PostCarousel'],
    'post-grid'          => ['name' => 'post-grid', 'class' => '\Zolo\Blocks\PostGrid'],
    'post-list'          => ['name' => 'post-list', 'class' => '\Zolo\Blocks\PostList'],
    'pricing-table'      => ['name' => 'pricing-table'],
    'profile-card'       => ['name' => 'profile-card'],
    'progress-bar'       => ['name' => 'progress-bar'],
    'progress-bar-child' => ['name' => 'progress-bar-child'],
    'progress-pie'       => ['name' => 'progress-pie'],
    'qrcode'             => ['name' => 'qrcode'],
    'review'             => ['name' => 'review'],
    'review-carousel'    => ['name' => 'review-carousel'],
    'review-child'       => ['name' => 'review-child'],
    'review-grid'        => ['name' => 'review-grid'],
    'slide'              => ['name' => 'slide'],
    'slider'             => ['name' => 'slider'],
    'social-links'       => ['name' => 'social-links'],
    'social-share'       => ['name' => 'social-share'],
    'star-rating'        => ['name' => 'star-rating'],
    'tab'                => ['name' => 'tab'],
    'tabs'               => ['name' => 'tabs'],
    'team-grid'          => ['name' => 'team-grid'],
    'team-child'         => ['name' => 'team-child'],
    'text-field'         => ['name' => 'text-field'],
    'text-path'          => ['name' => 'text-path'],
    'textarea'           => ['name' => 'textarea'],
    'post-category'      => ['name' => 'post-category', 'class' => '\Zolo\Blocks\PostCategory'],
    'tag-cloud'          => ['name' => 'tag-cloud', 'class' => '\Zolo\Blocks\TagCloud'],
    'post-list'          => ['name' => 'post-list', 'class' => '\Zolo\Blocks\PostList'],
    'lightbox'           => ['name' => 'lightbox'],
    'author'             => ['name' => 'author', 'class' => '\Zolo\Blocks\Author'],
    'social-count'       => ['name' => 'social-count'],
    'social-count-child' => ['name' => 'social-count-child'],
    'post-comments'      => ['name' => 'post-comments', 'class' => '\Zolo\Blocks\PostComments'],
    'breadcrumbs'        => ['name' => 'breadcrumbs', 'class' => '\Zolo\Blocks\BreadcrumbsBlock'],
    'post-timeline'      => ['name' => 'post-timeline', 'class' => '\Zolo\Blocks\PostTimeline'],
    'navmenu'            => ['name' => 'navmenu'],
    'navmenu-item'       => ['name' => 'navmenu-item'],
    'navmenu-submenu'    => ['name' => 'navmenu-submenu'],
    'megamenu'           => ['name' => 'megamenu'],
]);
