<?php
require_once ZOLO_DIR_PATH . 'includes/Blocks/PostGrid.php';
require_once ZOLO_DIR_PATH . 'includes/Blocks/PostList.php';

return apply_filters('zolo_blocks', [
    [
        'name'       => 'container',
        'title'      => __('Container', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'accordion',
        'title'      => __('Accordion', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'accordion-child',
        'title'      => __('Accordion Child', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => true,
    ],
    [
        'name'       => 'advanced-button',
        'title'      => __('Advanced Button', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'advanced-heading',
        'title'      => __('Advanced Heading', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'advanced-icon-box',
        'title'      => __('Advanced Icon Box', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'advanced-image',
        'title'      => __('Advanced Image', 'zoloblocks'),
        'categories' => ['gallery'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'advanced-search',
        'title'      => __('Advanced Search', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'brand-child',
        'title'      => __('Brand Child', 'zoloblocks'),
        'categories' => ['list'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => true,
    ],
    [
        'name'       => 'brand-grid',
        'title'      => __('Brand Grid', 'zoloblocks'),
        'categories' => ['list'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'business-hour',
        'title'      => __('Business Hour', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'charts',
        'title'      => __('Charts', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'countdown',
        'title'      => __('Countdown', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'counter',
        'title'      => __('Counter', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'cta',
        'title'      => __('Call to Action', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'email',
        'title'      => __('Email', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => true,
    ],
    [
        'name'       => 'fancy-list',
        'title'      => __('Fancy List', 'zoloblocks'),
        'categories' => ['list'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'fancy-list-child',
        'title'      => __('Fancy List Child', 'zoloblocks'),
        'categories' => ['list'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => true,
    ],
    [
        'name'       => 'flipbox',
        'title'      => __('Flipbox', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'form',
        'title'      => __('Form', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'google-map',
        'title'      => __('Google Map', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'icon',
        'title'      => __('Icon', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'image-compare',
        'title'      => __('Image Compare', 'zoloblocks'),
        'categories' => ['gallery'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'image-gallery',
        'title'      => __('Image Gallery', 'zoloblocks'),
        'categories' => ['gallery'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'list',
        'title'      => __('List', 'zoloblocks'),
        'categories' => ['list'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'newsletter',
        'title'      => __('Newsletter', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'notice',
        'title'      => __('Notice', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'popup-builder',
        'title'      => __('Popup Builder', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => true,
    ],
    [
        'name'       => 'post-carousel',
        'class'      => '\Zolo\Blocks\PostCarousel',
        'title'      => __('Post Carousel', 'zoloblocks'),
        'categories' => ['slider', 'postCategory'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
    ],
    [
        'name'       => 'post-grid',
        'class'      => '\Zolo\Blocks\PostGrid',
        'title'      => __('Post Grid', 'zoloblocks'),
        'categories' => ['list', 'postCategory'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'post-list',
        'class'      => '\Zolo\Blocks\PostList',
        'title'      => __('Post List', 'zoloblocks'),
        'categories' => ['list', 'postCategory'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'pricing-table',
        'title'      => __('Pricing Table', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'profile-card',
        'title'      => __('Profile Card', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'progress-bar',
        'title'      => __('Progress Bar', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
    ],
    [   
        'name'       => 'progress-bar-child',
        'title'      => __('Progress Bar Child', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => true,
    ],
    [
        'name'       => 'progress-pie',
        'title'      => __('Progress Pie', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'qrcode',
        'title'      => __('QR Code', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'review',
        'title'      => __('Review', 'zoloblocks'),
        'categories' => ['review'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'review-carousel',
        'title'      => __('Review Carousel', 'zoloblocks'),
        'categories' => ['review', 'slider'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'review-child',
        'title'      => __('Review Child', 'zoloblocks'),
        'categories' => ['review'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => true,
    ],
    [
        'name'       => 'review-grid',
        'title'      => __('Review Grid', 'zoloblocks'),
        'categories' => ['review', 'list'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'slide',
        'title'      => __('Slide', 'zoloblocks'),
        'categories' => ['slider'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => true,
    ],
    [
        'name'       => 'slider',
        'title'      => __('Slider', 'zoloblocks'),
        'categories' => ['slider'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'social-links',
        'title'      => __('Social Links', 'zoloblocks'),
        'categories' => ['social'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'social-share',
        'title'      => __('Social Share', 'zoloblocks'),
        'categories' => ['social'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [   
        'name'       => 'star-rating',
        'title'      => __('Star Rating', 'zoloblocks'),
        'categories' => ['review'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'tab',
        'title'      => __('Tab', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => true,
    ],
    [
        'name'       => 'tabs',
        'title'      => __('Tabs', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'team-child',
        'title'      => __('Team Child', 'zoloblocks'),
        'categories' => ['list'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => true,
    ],
    [
        'name'       => 'team-grid',
        'title'      => __('Team Grid', 'zoloblocks'),
        'categories' => ['list'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'text-field',
        'title'      => __('Text Field', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => true,
    ],
    [
        'name'       => 'text-path',
        'title'      => __('Text Path', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => false,
    ],
    [
        'name'       => 'textarea',
        'title'      => __('Textarea', 'zoloblocks'),
        'categories' => ['others'],
        'demo'       => 'https://zoloblocks.com/',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'status'     => true,
        'is_pro'     => false,
        'is_child'   => true,
    ],
]);
