name: Publish Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release-free:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install --force

      - name: Build
        run: npm run build

      - name: Archive release
        uses: thedoctor0/zip-release@0.7.6
        with:
          filename: 'zolo-blocks.zip'
          exclusions: '/src/* /*node_modules/* *.git* .distignore composer.lock Gruntfile.js webpack.config.js composer.json .editorconfig package.json package-lock.json README.md'


      - name: display release
        run: ls -a

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: './zolo-blocks.zip'
          token: ${{ secrets.TOKEN }}
          removeArtifacts: true
          allowUpdates: true
          makeLatest: true
          tag: ${{ github.ref_name }}
