name: Publish Release

on:
    push:
        tags:
            - '*'

permissions:
    contents: write

jobs:
    release-free:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install dependencies
              run: npm install --force

            - name: Build
              run: npm run build

            - name: Create zoloblocks directory and move files
              run: |
                  mkdir -p zoloblocks &&
                  find . -maxdepth 1 -not -name 'zoloblocks' -exec mv {} zoloblocks \;

            - name: Archive release
              uses: thedoctor0/zip-release@0.7.6
              with:
                  filename: 'zoloblocks.zip'
                  exclusions: '/*src/* /*node_modules/* /*.distignore /*.gitignore /*.github/* /*.git/* /*.editorconfig /*README.md /*Gruntfile.js /*package.json /*package-lock.json /*composer.lock /*webpack.config.js '
            - name: Display release
              run: ls -a

            - name: Create Release
              uses: ncipollo/release-action@v1.14.0
              with:
                  artifacts: './zoloblocks.zip'
                  token: ${{ secrets.TOKEN }}
                  removeArtifacts: true
                  allowUpdates: true
                  makeLatest: true
                  tag: ${{ github.ref_name }}
