name: Publish Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release-free:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0' # Specify the required PHP version
          extensions: mbstring, curl, zip # Add necessary PHP extensions
          tools: wp-cli # Install WP-CLI

      - name: Install dependencies
        run: npm install --force

      - name: Build
        run: npm run publish

      - name: Verify artifact exists
        run: ls -l ./zoloblocks.zip
        if: ${{ ! exists('./zoloblocks.zip') }}
        shell: bash

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: './zoloblocks.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
          removeArtifacts: true
          allowUpdates: true
          makeLatest: true
          tag: ${{ github.ref_name }}
